### ISSUE TITLE
Update the code to match the latest version API

### ISSUE THREAD

**Issue by ZhichengHuang** [Oneflow-Inc/OneFlow-Benchmark#92]
Due to the code use the older API, some case can't run successful, hope we can update the code.

**Comment by ShawnXuan** [comment]
BERT is using latest API.
CNN is using old API and will print warning when running. 

Would you please tell us which one failed, and provide more specific information, thanks!

**Comment by Flowingsun007** [comment]
> Due to the code use the older API, some case can't run successful, hope we can update the code.

We've updated code with new optimizer api,thanks for your suggestion !

**Comment by JF-D** [comment]
@Flowingsun007 When I run CNN benchmark, It failed. I use sync data and single V100 card. The error is as follow. Can you offer some help?
```
------------------------------------------------------------------
Time stamp: 2020-09-15-13:48:24
Traceback (most recent call last):
  File "of_cnn_train_val.py", line 64, in <module>
    @flow.global_function("train", get_train_config(args))
  File "/home/duanjiangfei/OneFlow-Benchmark/Classification/cnns/job_function_util.py", line 33, in get_train_config
    train_config = _default_config(args)
  File "/home/duanjiangfei/OneFlow-Benchmark/Classification/cnns/job_function_util.py", line 28, in _default_config
    config.enable_fuse_add_to_output(True)
  File "/home/duanjiangfei/.local.pt1.5s1/lib/python3.7/site-packages/oneflow/python/framework/function_util.py", line 54, in __getattr__
    assert attr_name in name2default
AssertionError
```
